### ISSUE TITLE
Crash on RN 60+ Android

### ISSUE THREAD

**Issue by bfarrgaynor** [FaridSafi/react-native-google-places-autocomplete#453]
We seem to be running into an error on RN 60 when running via android.
```
09-18 16:12:53.580 16629 16629 E AndroidRuntime: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'autoComplete' of a view managed by: AndroidTextInput
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:131)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:46)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:268)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:198)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1036)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1007)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:693)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6680)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$StringPropSetter.getValueOrDefault(ViewManagersPropertyCache.java:259)
09-18 16:12:53.580 16629 16629 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:82)
```

**Comment by FaisalAshraf44** [comment]
I'm experiencing the same issue. in android apk when I search for place app crashes. But it only happens once if close and reopen the app then it will work fine after crashing first time.

**Comment by bfarrgaynor** [comment]
Has there been any movement on this one? I'm having a heck of a time with this.

**Comment by bell-steven** [comment]
Hey @bfarrgaynor.  Would you be able to provide any sort of reproduction for this so I can dig into it?  A [Snack](https://snack.expo.io/) would be great, otherwise showing some code you are using.

**Comment by bell-steven** [comment]
I can't reproduce this. Please open a new issue if this problem persists.
