### ISSUE TITLE
Does not work without minor adjustments for Next.js

### ISSUE THREAD

**Issue by simplenotezy** [FaridSafi/react-native-google-places-autocomplete#712]
# Describe the problem

When using this library in Next.js you'll be  getting this error if you use Server Side Rendering:

```
react-dom.development.js?61bb:67 Warning: Prop `id` did not match. Server: "react-select-3-input" Client: "react-select-2-input"
    at input
    at div
    at n (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:30:9729)
    at div
    at EmotionCssPropInternal (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:24:26330)
    at Input (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:30:43293)
    at div
    at EmotionCssPropInternal (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:24:26330)
    at ValueContainer (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:30:45177)
    at div
    at EmotionCssPropInternal (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:24:26330)
    at Control (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:30:41831)
    at div
    at EmotionCssPropInternal (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:24:26330)
    at SelectContainer (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:30:44741)
    at o (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:30:68855)
    at o (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:30:97252)
    at r (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:30:94573)
```

# Solution

  When using GooglePlacesAutocomplete:

  ```javascript
    <NoSsr><GooglePlacesAutocomplete /></NoSsr>
  ```

The NoSSR component:
```javascript
import dynamic from 'next/dynamic';
import React from 'react';

const NoSsr = ({ children }) => <>{children}</>;

export default dynamic(() => Promise.resolve(NoSsr), {
  ssr: false,
});
```

It would be nice if this was documented somewhere, or perhaps even solved out of the box.

# Additional context

- Library Version: 2.2.0

- [ ] iOS
- [ ] Android
- [x] Web

**Comment by bell-steven** [comment]
Can you please post a working (minimal) code example?  The warning you have above is not a blocking error in my experience.

**Comment by simplenotezy** [comment]
It may not be a blocking error ,but it is still an error, perhaps because select2 gives a different ID on server and then on client.

Anyhow, I have already provided a code example - have a look at the NoSsr component above.
